<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Author - Linh Khanh Vo">
<meta name="author" content="Reviewer - Anitar Munár">
<meta name="dcterms.date" content="2023-03-21">

<title>Assigment - kNN DIY</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="assignment-knn-diy_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment-knn-diy_files/libs/quarto-html/quarto.js"></script>
<script src="assignment-knn-diy_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment-knn-diy_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment-knn-diy_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment-knn-diy_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment-knn-diy_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment-knn-diy_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment-knn-diy_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment-knn-diy_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assigment - kNN DIY</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Author - Linh Khanh Vo </p>
             <p>Reviewer - Anitar Munár </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 21, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="business-understanding" class="level2">
<h2 class="anchored" data-anchor-id="business-understanding">Business Understanding</h2>
<p>Diabetes prevents your body to turn food into energy. This can cause serious health problems, such as heart disease, vision loss, and kidney disease <span style="color:blue"><em>(What Is Diabetes?, 2022)</em></span>. Diabetes can be treated and be recognized early before it turns into an urgent case by doing some testing (blood glucose). Diabetes detection with early symptoms can reduce the death rate and prevent it from getting worse before it is too late. With machine learning algorithms, it could improve the accuracy and effectiveness of detection.</p>
</section>
<section id="data-understanding" class="level2">
<h2 class="anchored" data-anchor-id="data-understanding">Data Understanding</h2>
<p>The dataset is orginially retrieved from National Institute of Diabetes and Digestive and Kidney Diseases.With the result of diagnostic measurements, a patient is predicted to have diabetes or not. Donor database is Vincent Sigillito from RMI Group Leader Applied Physics Laboratory The Johns Hopkins University Johns Hopkins Road Laurel. The dataset used is downloaded from open source <span style="color:blue"><em>(Diabetes Dataset, 2020)</em></span>. The instances are females at least 21 years old of Pima Indian heritage.<br>
The dataset is stored in a Github repo and cloned into local repo. It is in .csv file. To read this, we use <code>readr</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>rawDF <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/data-mining-s2y2223-lynnevo170701/master/datasets/KNN-diabetes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By using <code>str()</code> function, we can have first sense of data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rawDF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [768 × 9] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Pregnancies             : num [1:768] 6 1 8 1 0 5 3 10 2 8 ...
 $ Glucose                 : num [1:768] 148 85 183 89 137 116 78 115 197 125 ...
 $ BloodPressure           : num [1:768] 72 66 64 66 40 74 50 0 70 96 ...
 $ SkinThickness           : num [1:768] 35 29 0 23 35 0 32 0 45 0 ...
 $ Insulin                 : num [1:768] 0 0 0 94 168 0 88 0 543 0 ...
 $ BMI                     : num [1:768] 33.6 26.6 23.3 28.1 43.1 25.6 31 35.3 30.5 0 ...
 $ DiabetesPedigreeFunction: num [1:768] 0.627 0.351 0.672 0.167 2.288 ...
 $ Age                     : num [1:768] 50 31 32 21 33 30 26 29 53 54 ...
 $ Outcome                 : num [1:768] 1 0 1 0 1 0 1 0 1 1 ...
 - attr(*, "spec")=
  .. cols(
  ..   Pregnancies = col_double(),
  ..   Glucose = col_double(),
  ..   BloodPressure = col_double(),
  ..   SkinThickness = col_double(),
  ..   Insulin = col_double(),
  ..   BMI = col_double(),
  ..   DiabetesPedigreeFunction = col_double(),
  ..   Age = col_double(),
  ..   Outcome = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>The dimension of dataset is 768 x 9, which means that the data has 768 observations and 9 variables:</p>
<p>- <code>Pregnancies</code>: Number of times pregnant</p>
<p>- <code>Glucose</code>: Plasma glucose concentration a 2 hours in an oral glucose tolerance test - <code>BloodPressure</code>: Diastolic blood pressure (mm Hg)</p>
<p>- <code>SkinThickness</code>: Triceps skin fold thickness (mm)</p>
<p>- <code>Insulin</code>: 2-Hour serum insulin (mu U/ml)</p>
<p>- <code>BMI</code>: Body mass index (weight in kg/(height in m)^2)</p>
<p>- <code>DiabetesPedigreeFunction</code>: Diabetes pedigree function</p>
<p>- <code>Age</code>: Age (years)</p>
<p>- <code>Outcome</code>: Class variable (0 or 1)</p>
<p>The data type of all variables are <code>num</code>. We can use <code>summary</code> function to see the summary information of each variable and we can check if each has Nas values, which we need to clean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rawDF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Pregnancies        Glucose      BloodPressure    SkinThickness  
 Min.   : 0.000   Min.   :  0.0   Min.   :  0.00   Min.   : 0.00  
 1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 62.00   1st Qu.: 0.00  
 Median : 3.000   Median :117.0   Median : 72.00   Median :23.00  
 Mean   : 3.845   Mean   :120.9   Mean   : 69.11   Mean   :20.54  
 3rd Qu.: 6.000   3rd Qu.:140.2   3rd Qu.: 80.00   3rd Qu.:32.00  
 Max.   :17.000   Max.   :199.0   Max.   :122.00   Max.   :99.00  
    Insulin           BMI        DiabetesPedigreeFunction      Age       
 Min.   :  0.0   Min.   : 0.00   Min.   :0.0780           Min.   :21.00  
 1st Qu.:  0.0   1st Qu.:27.30   1st Qu.:0.2437           1st Qu.:24.00  
 Median : 30.5   Median :32.00   Median :0.3725           Median :29.00  
 Mean   : 79.8   Mean   :31.99   Mean   :0.4719           Mean   :33.24  
 3rd Qu.:127.2   3rd Qu.:36.60   3rd Qu.:0.6262           3rd Qu.:41.00  
 Max.   :846.0   Max.   :67.10   Max.   :2.4200           Max.   :81.00  
    Outcome     
 Min.   :0.000  
 1st Qu.:0.000  
 Median :0.000  
 Mean   :0.349  
 3rd Qu.:1.000  
 Max.   :1.000  </code></pre>
</div>
</div>
<p>Then we should check if the data has duplicated values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dup_check <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(rawDF))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dup_check</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data Preparation</h2>
<p>The <code>outcome</code> variable has the values we need to predict “0 - negative” and “1 - positive”.We need to set level and label for it to easily sort or call it later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rawDF<span class="sc">$</span>Outcome <span class="ot">&lt;-</span> <span class="fu">factor</span>(rawDF<span class="sc">$</span>Outcome, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Negative"</span>, <span class="st">"Positive"</span>)) <span class="sc">%&gt;%</span>  <span class="fu">relevel</span>(<span class="st">"Positive"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can clearly see that the variables have different ranges. We need to normalize it before splitting into train and test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>normalize <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> ((x <span class="sc">-</span> <span class="fu">min</span>(x)) <span class="sc">/</span> (<span class="fu">max</span>(x) <span class="sc">-</span> <span class="fu">min</span>(x)))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>cleanDF <span class="ot">&lt;-</span> rawDF </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>cleanDF[,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>] <span class="ot">&lt;-</span> <span class="fu">normalize</span>(cleanDF[,<span class="dv">1</span><span class="sc">:</span>(<span class="fu">ncol</span>(rawDF)<span class="sc">-</span><span class="dv">1</span>)])</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cleanDF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Pregnancies          Glucose       BloodPressure     SkinThickness    
 Min.   :0.000000   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.001182   1st Qu.:0.1170   1st Qu.:0.07329   1st Qu.:0.00000  
 Median :0.003546   Median :0.1383   Median :0.08511   Median :0.02719  
 Mean   :0.004545   Mean   :0.1429   Mean   :0.08168   Mean   :0.02427  
 3rd Qu.:0.007092   3rd Qu.:0.1658   3rd Qu.:0.09456   3rd Qu.:0.03783  
 Max.   :0.020095   Max.   :0.2352   Max.   :0.14421   Max.   :0.11702  
    Insulin             BMI          DiabetesPedigreeFunction      Age         
 Min.   :0.00000   Min.   :0.00000   Min.   :0.0000922        Min.   :0.02482  
 1st Qu.:0.00000   1st Qu.:0.03227   1st Qu.:0.0002881        1st Qu.:0.02837  
 Median :0.03605   Median :0.03783   Median :0.0004403        Median :0.03428  
 Mean   :0.09433   Mean   :0.03782   Mean   :0.0005578        Mean   :0.03929  
 3rd Qu.:0.15041   3rd Qu.:0.04326   3rd Qu.:0.0007402        3rd Qu.:0.04846  
 Max.   :1.00000   Max.   :0.07931   Max.   :0.0028605        Max.   :0.09574  
     Outcome   
 Positive:268  
 Negative:500  
               
               
               
               </code></pre>
</div>
</div>
<p>After running <code>summary</code>, we see that normalization has set all the parameters into the same range Now, we split our data into training and test sets by using <code>train_test_split</code> from package <code>creditmodel</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>test_train <span class="ot">&lt;-</span> <span class="fu">train_test_split</span>(cleanDF)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test_train[[<span class="dv">1</span>]]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> test_train[[<span class="dv">2</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These two data frames inclue <code>outcome</code>. But we only need parameters without <code>outcome</code> variable to set as <code>train_feat</code> or `test_feat, so we will exclude that variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>test_feat <span class="ot">&lt;-</span> test[<span class="sc">-</span><span class="dv">9</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>train_feat <span class="ot">&lt;-</span> train[<span class="sc">-</span><span class="dv">9</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Creating labels for training and test set</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>test_labels <span class="ot">&lt;-</span> test[, <span class="dv">9</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>train_labels <span class="ot">&lt;-</span> train[,<span class="dv">9</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modeling" class="level2">
<h2 class="anchored" data-anchor-id="modeling">Modeling</h2>
<p>I will use <code>knn</code> from package <code>class</code>. It takes the set with <code>train_feat</code> and the set with <code>train_labels</code>. The trained model is applied to the set with <code>test_feat</code> and it will return a set of predictions. First, I find the optimal <code>k</code> value to make the knn has the lowest error rate by creating function <code>error_k</code> with the argument <code>k</code>. <code>error_k</code> will return a data frame of <code>error_rate</code> values corresponding to <code>k</code> values. Using <code>relevel</code> function to prevent the warning message ” Levels are not in the same order for reference and data. Refactoring data to match” when running <code>confusionMatrix</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>error_k <span class="ot">&lt;-</span> <span class="cf">function</span>(k) {</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  error_rate <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> k) {</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>      knn <span class="ot">&lt;-</span> <span class="fu">knn</span>(<span class="at">train =</span> <span class="fu">as.matrix</span>(train_feat), <span class="at">test =</span> <span class="fu">as.matrix</span>(test_feat), <span class="at">cl =</span> <span class="fu">as.matrix</span>(train_labels), <span class="at">k =</span> i)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>      knn <span class="ot">&lt;-</span> <span class="fu">relevel</span>(knn, <span class="st">"Positive"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>      matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(knn, test_labels[[<span class="dv">1</span>]], <span class="at">positive =</span> <span class="cn">NULL</span>, <span class="at">dnn =</span> <span class="fu">c</span>(<span class="st">"Prediction"</span>, <span class="st">"True"</span>))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>      error_rate <span class="ot">&lt;-</span> <span class="fu">rbind</span>(error_rate, <span class="dv">1</span><span class="sc">-</span>matrix<span class="sc">$</span>overall[[<span class="st">"Accuracy"</span>]])</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  error_k <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(k, error_rate)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(error_k) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"k"</span>, <span class="st">"error_rate"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  error_k</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, I will plot the error rate with k from 1 to 40.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">&lt;-</span> <span class="fu">error_k</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot, <span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> error_rate )) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">0.7</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Error Rate vs k value"</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Error Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment-knn-diy_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As shown in the graph, k = 10 will return the lowest error rate. 10 will be used as the amount of nearest neighbours <code>k</code> in <code>knn</code> function below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cleanDF_test_pred <span class="ot">&lt;-</span> <span class="fu">knn</span>(<span class="at">train =</span> <span class="fu">as.matrix</span>(train_feat), <span class="at">test =</span> <span class="fu">as.matrix</span>(test_feat), <span class="at">cl =</span> <span class="fu">as.matrix</span>(train_labels), <span class="at">k =</span> <span class="dv">10</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cleanDF_test_pred <span class="ot">&lt;-</span> <span class="fu">relevel</span>(cleanDF_test_pred, <span class="st">"Positive"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cleanDF_test_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Positive Positive Negative Negative Negative Negative
Levels: Positive Negative</code></pre>
</div>
</div>
<p>We have predicted labels. We will compare them with actual labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(cleanDF_test_pred, test_labels[[<span class="dv">1</span>]], <span class="at">positive =</span> <span class="cn">NULL</span>, <span class="at">dnn =</span> <span class="fu">c</span>(<span class="st">"Prediction"</span>, <span class="st">"True"</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>cf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          True
Prediction Positive Negative
  Positive       47       18
  Negative       46      119
                                         
               Accuracy : 0.7217         
                 95% CI : (0.659, 0.7786)
    No Information Rate : 0.5957         
    P-Value [Acc &gt; NIR] : 4.575e-05      
                                         
                  Kappa : 0.393          
                                         
 Mcnemar's Test P-Value : 0.0007382      
                                         
            Sensitivity : 0.5054         
            Specificity : 0.8686         
         Pos Pred Value : 0.7231         
         Neg Pred Value : 0.7212         
             Prevalence : 0.4043         
         Detection Rate : 0.2043         
   Detection Prevalence : 0.2826         
      Balanced Accuracy : 0.6870         
                                         
       'Positive' Class : Positive       
                                         </code></pre>
</div>
</div>
<p>To visualize the confusion matrix, I will use <code>plot_confusion_matrix</code> function from package <code>cvms</code>. First I need to convert matrix type of <code>cf</code> to tibble because this function only accepts data.frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(cf<span class="sc">$</span>table)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_confusion_matrix</span>(table, <span class="at">target_col =</span> <span class="st">"True"</span>, <span class="at">prediction_col =</span> <span class="st">"Prediction"</span>, <span class="at">counts_col =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot_confusion_matrix(table, target_col = "True", prediction_col =
"Prediction", : 'ggimage' is missing. Will not plot arrows and zero-shading.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot_confusion_matrix(table, target_col = "True", prediction_col =
"Prediction", : 'rsvg' is missing. Will not plot arrows and zero-shading.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Ignoring unknown parameters: linewidth</code></pre>
</div>
<div class="cell-output-display">
<p><img src="assignment-knn-diy_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="evaluation-and-deployment" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-and-deployment">Evaluation and Deployment</h2>
<p>Overall, the accuracy percentage is 72.1%. 51.7% of test feature has True Negative and 20.4% is True Positive. 7.8% is False positive and 20% is False negative.</p>
<p>Of the 230 cases, 93 are positive (47 TPs and 46 FNs) and 137 are negative (119 TNs and 18 FPs).</p>
<p>Of 137 negative diabetes, 86.9% are correctly predicted. This is a good result.</p>
<p>However, of 93 positive cases, only 50.5% are correctly identified. Half of the cases go wrong. This is a bad outcome.</p>
<p><strong>Precision</strong> in this model is 72.3%. Precision tells us that when it predicts someone is positive, 72.3% of the time is correct.</p>
<p><strong>Recall</strong> in this model is 50.5%. Recall is quite high and Precision is quite low. This can be improved by increasing the classification threshold.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>What is Diabetes? (2022, July 7). Centers for Disease Control and Prevention. <a href="https://www.cdc.gov/diabetes/basics/diabetes.html" class="uri">https://www.cdc.gov/diabetes/basics/diabetes.html</a></li>
<li>Diabetes Dataset. (2020, August 5). Kaggle. <a href="https://www.kaggle.com/datasets/mathchi/diabetes-data-set" class="uri">https://www.kaggle.com/datasets/mathchi/diabetes-data-set</a></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>